;(function(d){var k=d.scrollTo=function(a,i,e){d(window).scrollTo(a,i,e)};k.defaults={axis:'xy',duration:parseFloat(d.fn.jquery)>=1.3?0:1};k.window=function(a){return d(window)._scrollable()};d.fn._scrollable=function(){return this.map(function(){var a=this,i=!a.nodeName||d.inArray(a.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!i)return a;var e=(a.contentWindow||a).document||a.ownerDocument||a;return d.browser.safari||e.compatMode=='BackCompat'?e.body:e.documentElement})};d.fn.scrollTo=function(n,j,b){if(typeof j=='object'){b=j;j=0}if(typeof b=='function')b={onAfter:b};if(n=='max')n=9e9;b=d.extend({},k.defaults,b);j=j||b.speed||b.duration;b.queue=b.queue&&b.axis.length>1;if(b.queue)j/=2;b.offset=p(b.offset);b.over=p(b.over);return this._scrollable().each(function(){var q=this,r=d(q),f=n,s,g={},u=r.is('html,body');switch(typeof f){case'number':case'string':if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(f)){f=p(f);break}f=d(f,this);case'object':if(f.is||f.style)s=(f=d(f)).offset()}d.each(b.axis.split(''),function(a,i){var e=i=='x'?'Left':'Top',h=e.toLowerCase(),c='scroll'+e,l=q[c],m=k.max(q,i);if(s){g[c]=s[h]+(u?0:l-r.offset()[h]);if(b.margin){g[c]-=parseInt(f.css('margin'+e))||0;g[c]-=parseInt(f.css('border'+e+'Width'))||0}g[c]+=b.offset[h]||0;if(b.over[h])g[c]+=f[i=='x'?'width':'height']()*b.over[h]}else{var o=f[h];g[c]=o.slice&&o.slice(-1)=='%'?parseFloat(o)/100*m:o}if(/^\d+$/.test(g[c]))g[c]=g[c]<=0?0:Math.min(g[c],m);if(!a&&b.queue){if(l!=g[c])t(b.onAfterFirst);delete g[c]}});t(b.onAfter);function t(a){r.animate(g,j,b.easing,a&&function(){a.call(this,n,b)})}}).end()};k.max=function(a,i){var e=i=='x'?'Width':'Height',h='scroll'+e;if(!d(a).is('html,body'))return a[h]-d(a)[e.toLowerCase()]();var c='client'+e,l=a.ownerDocument.documentElement,m=a.ownerDocument.body;return Math.max(l[h],m[h])-Math.min(l[c],m[c])};function p(a){return typeof a=='object'?a:{top:a,left:a}}})(jQuery);
;(function($){var l=location.href.replace(/#.*/,'');var g=$.localScroll=function(a){$('body').localScroll(a)};g.defaults={duration:1e3,axis:'y',event:'click',stop:true,target:window,reset:true};g.hash=function(a){if(location.hash){a=$.extend({},g.defaults,a);a.hash=false;if(a.reset){var e=a.duration;delete a.duration;$(a.target).scrollTo(0,a);a.duration=e}i(0,location,a)}};$.fn.localScroll=function(b){b=$.extend({},g.defaults,b);return b.lazy?this.bind(b.event,function(a){var e=$([a.target,a.target.parentNode]).filter(d)[0];if(e)i(a,e,b)}):this.find('a,area').filter(d).bind(b.event,function(a){i(a,this,b)}).end().end();function d(){return!!this.href&&!!this.hash&&this.href.replace(this.hash,'')==l&&(!b.filter||$(this).is(b.filter))}};function i(a,e,b){var d=e.hash.slice(1),f=document.getElementById(d)||document.getElementsByName(d)[0];if(!f)return;if(a)a.preventDefault();var h=$(b.target);if(b.lock&&h.is(':animated')||b.onBefore&&b.onBefore.call(b,a,f,h)===false)return;if(b.stop)h.stop(true);if(b.hash){var j=f.id==d?'id':'name',k=$('<a> </a>').attr(j,d).css({position:'absolute',top:$(window).scrollTop(),left:$(window).scrollLeft()});f[j]='';$('body').prepend(k);location=e.hash;k.remove();f[j]=d}h.scrollTo(f,b).trigger('notify.serialScroll',[f])}})(jQuery);;(function($){var on=$.fn.on,timer;$.fn.on=function(){var args=Array.apply(null,arguments);var last=args[args.length- 1];if(isNaN(last)||(last===1&&args.pop()))return on.apply(this,args);var delay=args.pop()
var fn=args.pop();args.push(function(){var self=this,params=arguments;clearTimeout(timer);timer=setTimeout(function(){fn.apply(self,params);},delay);});return on.apply(this,args);};})(jQuery);(function($){$.fn.toggleMultistateClass=function(classNames,setClass){var numClassNames=classNames.length;for(var i=0;i<numClassNames;i++){var className=classNames[i];if(this.hasClass(className)){this.removeClass(className);if(setClass===undefined)
setClass=(i+1)%numClassNames;else if(typeof setClass=="object")
setClass=setClass[i];}}
if(typeof setClass=="number")
setClass=classNames[setClass]
this.addClass(setClass);}})(jQuery)
jQuery(function($){$("body").addClass("js");$.localScroll();$("#mobile-menu select").change(function(){var link=$(this).val();if(link!="")window.location="http://www.dailycal.org"+ link;});$('[placeholder]').focus(function(){var input=$(this);if(input.val()==input.attr('placeholder')){input.val('');input.removeClass('placeholder');}}).blur(function(){var input=$(this);if(input.val()==''||input.val()==input.attr('placeholder')){input.addClass('placeholder');input.val(input.attr('placeholder'));}}).blur().parents('form').submit(function(){$(this).find('[placeholder]').each(function(){var input=$(this);if(input.val()==input.attr('placeholder')){input.val('');}});});$('.site-navigation-search .search-field').focus(function(){$(".js-disappear-with-search").addClass("var-disappear");}).blur(function(){$(".js-disappear-with-search").removeClass("var-disappear");});if($('.js-site-nav-target').length>0){$(window).scroll((function(){var threshold=1000;var element=document.getElementsByClassName('js-site-nav-target')[0];var filler=document.getElementsByClassName('js-site-nav-filler')[0];var thresholdoffset=($('body').hasClass('admin-bar'))?-32:0;threshold+=thresholdoffset;for(var i=1;i<18;i++){setTimeout((function(){return function(){threshold=$(".js-site-nav-filler").offset()['top']+ thresholdoffset;};})(),i*1000);}
return function(){if(window.scrollY>=threshold){filler.classList.add('var-filling');element.classList.add('var-fixed');}else{filler.classList.remove('var-filling');element.classList.remove('var-fixed');}};})());}
if($('[id^=div-gpt-ad-]').css('display')=='none'){var page_ad=$('.supporter-entry');page_ad.empty();page_ad.css({padding:'20px',margin:'0',textAlign:'center',color:'white',lineHeight:1.5,});page_ad.html('Please consider turning off Adblock or <a href="http://donate.dailycal.org/donate/?utm_source=internal&utm_medium=ad&utm_campaign=adblock&utm_content=page_ad">donating to The Daily Californian</a>.<br />We are a nonprofit student-run newsroom, and we rely on advertising revenue to help support our coverage.');$('.supporter-entry a').css('color','#62BAFF');}
$('.site-primary-menu-toggle .js-toggle').click(function(){$('.site-nav').css('height','auto');$(this).hide();});$(".entry-content blockquote").each(function(index,e){var is_pull_quote=true;$(e).children().each(function(index,c){if($(c).css('text-align')!='right'){is_pull_quote=false;}});if(is_pull_quote){$(e).addClass('var-pull-quote');}});$.extend($.expr[":"],{reallyvisible:function(a){return!($(a).is(':hidden')||$(a).parents(':hidden').length);}});if($(".site-primary-nav .sub-menu:reallyvisible").length){$(".js-site-nav-target, .js-site-nav-filler").addClass("var-expanded");}
var cookie={create:function(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/";},erase:function(name){cookie.create(name,"",-1);},read:function(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;},}
var query={update:function(uri,key,value){var hashIndex=uri.indexOf("#");if(hashIndex==-1)hashIndex=uri.length
var hash=uri.substring(hashIndex);uri=uri.substring(0,hashIndex)
var re=new RegExp("([?&])"+ key+"=.*?(&|$)","i");var separator=uri.indexOf('?')!==-1?"&":"?";if(uri.match(re)){return uri.replace(re,'$1'+ key+"="+ value+'$2')+ hash;}
else{return uri+ separator+ key+"="+ value+ hash;}},read:function(uri,key){var hashIndex=uri.indexOf("#");if(hashIndex==-1)hashIndex=uri.length
var hash=uri.substring(hashIndex);uri=uri.substring(0,hashIndex)
var re=new RegExp("([?&])"+ key+"=(.*?)(&|$)","i");var separator=uri.indexOf('?')!==-1?"&":"?";var match=uri.match(re);return match?match[2]:null;},}
var presentation={DEBUG:true,query:{get:function(){var PARAM="presentation";return query.read(location.href,PARAM);},updateUrl:function(value){var PARAM="presentation";if(value){if(presentation.DEBUG)console.log('setting presentation parameter: '+ value);return query.update(location.href,PARAM,value);}
else{throw Error("unsetting presentation parameter not implemented");}},updateLink:function(sel,value){if(presentation.DEBUG)
$(sel).each(function(i,el){console.log('updating query link: ',el,value);})
$(sel).attr('href',presentation.query.updateUrl(value));presentation.cookie.updateLinkPreventOthers(sel);},init:function(){presentation.query.updateLink('.site-link-presentation-param-desktop','desktop');presentation.query.updateLink('.site-link-presentation-param-mobile','mobile');}},cookie:{set:function(value){var COOKIE="dc_presentation";if(value){cookie.create(COOKIE,value);if(presentation.DEBUG)console.log('setting presentation cookie: '+ value,'; document.cookie = '+ document.cookie);}
else{cookie.erase(COOKIE);if(presentation.DEBUG)console.log('erasing presentation cookie','; document.cookie = '+ document.cookie);}},updateLinkPreventOthers:function(sel,value){$(sel).click(function(event){presentation.cookie.set(value);})},updateLink:function(sel,value){var $el=$(sel);$el.click(function(event){event.preventDefault();presentation.cookie.set(value);$el.css('opacity','0.5');return false;}).attr('href','');},init:function(){presentation.cookie.updateLink('.site-link-presentation-cookie-desktop','desktop');presentation.cookie.updateLink('.site-link-presentation-cookie-mobile','mobile');presentation.cookie.updateLink('.site-link-presentation-cookie-undefined');if(presentation.query.get())$('.site-link-presentation-cookie').removeClass('hidden');},},ua:{isMobile:function(){var smartphones=new RegExp("(android|bb\\d+|meego).+mobile|avantgo|bada\\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino","gi");var stupidphones=new RegExp("^(1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\\-(n|u)|c55\\/|capi|ccwa|cdm\\-|cell|chtm|cldc|cmd\\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\\-s|devi|dica|dmob|do(c|p)o|ds(12|\\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\\-|_)|g1 u|g560|gene|gf\\-5|g\\-mo|go(\\.w|od)|gr(ad|un)|haie|hcit|hd\\-(m|p|t)|hei\\-|hi(pt|ta)|hp( i|ip)|hs\\-c|ht(c(\\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\\-(20|go|ma)|i230|iac( |\\-|\\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\\/)|klon|kpt |kwc\\-|kyo(c|k)|le(no|xi)|lg( g|\\/(k|l|u)|50|54|\\-[a-w])|libw|lynx|m1\\-w|m3ga|m50\\/|ma(te|ui|xo)|mc(01|21|ca)|m\\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\\-2|po(ck|rt|se)|prox|psio|pt\\-g|qa\\-a|qc(07|12|21|32|60|\\-[2-7]|i\\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\\-|oo|p\\-)|sdk\\/|se(c(\\-|0|1)|47|mc|nd|ri)|sgh\\-|shar|sie(\\-|m)|sk\\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\\-|v\\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\\-|tdg\\-|tel(i|m)|tim\\-|t\\-mo|to(pl|sh)|ts(70|m\\-|m3|m5)|tx\\-9|up(\\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\\-|your|zeto|zte\\-)","gi");return smartphones.test(navigator.userAgent)||stupidphones.test(navigator.userAgent);},},init:function(){presentation.query.init();presentation.cookie.init();},}
presentation.init();if(!window.DC)window.DC={}
window.DC.presentation=presentation;var updateSiteHeader=function(evt){var $el=$('#header');var classNames=['floating','static'];if(pageYOffset>102+30)
$el.toggleMultistateClass(classNames,0)
else if(pageYOffset>102)
$el.toggleMultistateClass(classNames,0)
else
$el.toggleMultistateClass(classNames,1)
return false;}
var overlayStates=['no-overlay','site-menu-expanded','site-search-expanded'];var overlaySiteMenuTargetStates=[1,0,1];var overlaySiteSearchTargetStates=[2,2,0];var overlaySiteOverlayTargetStates=0;var toggleSiteMenu=function(evt){$('html').toggleMultistateClass(overlayStates,overlaySiteMenuTargetStates);evt.preventDefault();return false;}
$('.toggle-site-menu').click(toggleSiteMenu);var toggleSiteSearch=function(evt){$('html').toggleMultistateClass(overlayStates,overlaySiteSearchTargetStates);evt.preventDefault();return false;}
$('.toggle-site-search').click(toggleSiteSearch);$('html').toggleMultistateClass(overlayStates,0);var toggleSiteOverlay=function(evt){$('html').toggleMultistateClass(overlayStates,overlaySiteOverlayTargetStates);evt.preventDefault();return false;};$('.site-menu-overlay').click(toggleSiteOverlay);var homeSectionStates=['show-none','show-teaser','show-all'];var homeSectionTargetStates=[1,0,0];var showHomeSection=function(evt){var $section=$(this).closest('#sections > .section');$section.toggleMultistateClass(homeSectionStates,2);evt.preventDefault();return false;}
$('.show-home-section').click(showHomeSection);var toggleHomeSection=function(evt){var $section=$(this).closest('#sections > .section');$section.toggleMultistateClass(homeSectionStates,homeSectionTargetStates);evt.preventDefault();return false;}
$('.toggle-home-section').click(toggleHomeSection);});